AllCops:
  TargetRubyVersion: 2.4
  DisplayCopNames: true
  Exclude:
    - vendor/**/*
    - bin/**

Metrics/AbcSize:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma
